platform :ios, '16.0'

target 'SDK Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDK Sample
  pod 'LucraSDK', :podspec => '../LucraSDK.podspec'

  target 'SDK SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDK SampleUITests' do
    # Pods for testing
  end

end
