source 'https://github.com/Lucra-Sports/lucra-ios-sdk'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16.0'

target 'CocoaPodsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDK Sample
  #pod 'LucraSDK'

  pod 'LucraSDK', :podspec => '../../LucraSDK.podspec'

end
