source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16.0'

target 'CocoaPodsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #pod 'LucraSDK', :podspec => '../../LucraSDK.podspec'

  # In your app use standard pod syntax
  pod 'LucraSDK', '~> 1.3.4'
end
